sudo: required
services:
    - docker

before_install:
    - docker build -t patrangada/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true patrangada/react-test npm test

after_sucess: 
    - docker build -t patrangada/multi-client ./client
    - docker build -t patrangada/multi-nginx ./nginx
    - docker build -t patrangada/multi-server ./server
    - docker build -t patrangada/multi-worker ./worker
    #Log into the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
    #Take above images and push them to docker hub
    - docker push patrangada/multi-client
    - docker push patrangada/multi-nginx
    - docker push patrangada/multi-server
    - docker push patrangada/multi-worker

    deploy:
        edge: true
        provider: elasticbeanstalk
        region: us-east-1
        app: multi-docker
        env: MultiDocker-env
        bucket_name: elasticbeanstalk-us-east-1-131140083519
        on:
            branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY

